from __future__ import annotations

from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "AFA-other" / "model_ready" / "forecast_weather"
OUT_DIR = ROOT / "AFA-other" / "model_ready" / "trainable_forecast_weather"

CROPS = ["cabbage", "bok_choy", "cauliflower", "green_onion", "lettuce"]
HORIZONS = [1, 5, 7, 14, 20]

EXCLUDE_FROM_FEATURES = {
    "ds",
    "y",
    "price_avg_weighted",
    "price_mean",
    "high_price_weighted",
    "mid_price_weighted",
    "low_price_weighted",
}


def build_horizon_frame(crop: str, horizon: int) -> tuple[pd.DataFrame, pd.DataFrame, list[str]]:
    full = pd.read_csv(SRC_DIR / f"{crop}_daily.csv", parse_dates=["ds"]).sort_values("ds")
    train_dates = pd.read_csv(SRC_DIR / f"{crop}_daily_train.csv", usecols=["ds"], parse_dates=["ds"])
    test_dates = pd.read_csv(SRC_DIR / f"{crop}_daily_test.csv", usecols=["ds"], parse_dates=["ds"])
    test_date_set = set(test_dates["ds"])

    df = full.copy()
    df["current_price"] = df["y"]
    df["target_date"] = df["ds"].shift(-horizon)
    df[f"target_h{horizon}"] = df["y"].shift(-horizon)
    df[f"target_return_h{horizon}"] = (df[f"target_h{horizon}"] - df["y"]) / df["y"]
    df[f"target_up_h{horizon}"] = (df[f"target_return_h{horizon}"] >= 0).astype(int)
    df[f"target_rise_ge_5pct_h{horizon}"] = (df[f"target_return_h{horizon}"] >= 0.05).astype(int)
    df[f"target_rise_ge_10pct_h{horizon}"] = (df[f"target_return_h{horizon}"] >= 0.10).astype(int)
    df = df.dropna(subset=["target_date", f"target_h{horizon}"]).reset_index(drop=True)

    target_cols = [
        f"target_h{horizon}",
        f"target_return_h{horizon}",
        f"target_up_h{horizon}",
        f"target_rise_ge_5pct_h{horizon}",
        f"target_rise_ge_10pct_h{horizon}",
    ]
    feature_cols = [
        c for c in df.columns
        if c not in EXCLUDE_FROM_FEATURES
        and c not in {"target_date", *target_cols}
        and pd.api.types.is_numeric_dtype(df[c])
    ]

    # Split by target date: a row goes to test only when the predicted date is
    # inside the original test period. This avoids training on labels from the
    # held-out future period.
    test = df[df["target_date"].isin(test_date_set)].copy()
    train = df[~df["target_date"].isin(test_date_set)].copy()

    ordered_cols = ["ds", "target_date", *feature_cols, *target_cols]
    return train[ordered_cols], test[ordered_cols], feature_cols


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    summary = []

    for crop in CROPS:
        crop_dir = OUT_DIR / crop
        crop_dir.mkdir(parents=True, exist_ok=True)
        for horizon in HORIZONS:
            train, test, feature_cols = build_horizon_frame(crop, horizon)
            train.to_csv(crop_dir / f"{crop}_h{horizon}_train.csv", index=False, encoding="utf-8-sig")
            test.to_csv(crop_dir / f"{crop}_h{horizon}_test.csv", index=False, encoding="utf-8-sig")
            (crop_dir / f"{crop}_h{horizon}_features.txt").write_text(
                "\n".join(feature_cols) + "\n",
                encoding="utf-8",
            )
            summary.append((crop, horizon, len(train), len(test), len(feature_cols)))
            print(f"{crop} h{horizon}: train={len(train)}, test={len(test)}, features={len(feature_cols)}")

    lines = [
        "# Trainable forecast data with weather",
        "",
        "Generated by `scripts/prepare_trainable_forecast_weather.py`.",
        "",
        "Each row uses information available at date `ds` to predict a future target date.",
        "",
        "Targets:",
        "",
        "- `target_h{h}`: future weighted average price after h days.",
        "- `target_return_h{h}`: future percentage change from current `y`.",
        "- `target_up_h{h}`: classification target for price increase.",
        "- `target_rise_ge_5pct_h{h}`: classification target for >=5% increase.",
        "- `target_rise_ge_10pct_h{h}`: classification target for >=10% increase.",
        "",
        "Split rule: train/test is determined by `target_date`, so rows whose labels fall in the original test period are held out.",
        "",
        "| crop | horizon_days | train_rows | test_rows | feature_count |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for crop, horizon, train_n, test_n, feature_n in summary:
        lines.append(f"| {crop} | {horizon} | {train_n} | {test_n} | {feature_n} |")
    (OUT_DIR / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Done. Output: {OUT_DIR}")


if __name__ == "__main__":
    main()
