from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
FORECAST_DIR = ROOT / "AFA-other" / "model_ready" / "forecast"
OUT_DIR = ROOT / "AFA-other" / "model_ready" / "forecast_weather"
WEATHER_PATH = ROOT / "天氣資料.csv"
CROPS = ["cabbage", "bok_choy", "cauliflower", "green_onion", "lettuce"]


def load_weather() -> pd.DataFrame:
    df = pd.read_csv(WEATHER_PATH, parse_dates=["觀測日期"])
    df = df.rename(
        columns={
            "觀測日期": "ds",
            "平均溫度(°C)": "weather_temp_avg",
            "最高溫度(°C)": "weather_temp_max",
            "最低溫度(°C)": "weather_temp_min",
            "降雨量(mm)": "weather_rainfall_mm",
            "相對濕度(%)": "weather_humidity_pct",
        }
    )

    daily = (
        df.groupby("ds")
        .agg(
            weather_county_count=("縣市", "nunique"),
            weather_temp_avg=("weather_temp_avg", "mean"),
            weather_temp_max=("weather_temp_max", "max"),
            weather_temp_min=("weather_temp_min", "min"),
            weather_rainfall_mean=("weather_rainfall_mm", "mean"),
            weather_rainfall_max=("weather_rainfall_mm", "max"),
            weather_rainfall_total=("weather_rainfall_mm", "sum"),
            weather_humidity_avg=("weather_humidity_pct", "mean"),
        )
        .reset_index()
        .sort_values("ds")
    )

    value_cols = [c for c in daily.columns if c != "ds"]
    daily[value_cols] = daily[value_cols].ffill().bfill()

    for base in ["weather_temp_avg", "weather_rainfall_mean", "weather_rainfall_max", "weather_humidity_avg"]:
        daily[f"{base}_lag_1"] = daily[base].shift(1)
        daily[f"{base}_lag_3"] = daily[base].shift(3)

    for window in [3, 7, 14]:
        daily[f"weather_rainfall_mean_sum_{window}d"] = daily["weather_rainfall_mean"].shift(1).rolling(window, min_periods=1).sum()
        daily[f"weather_rainfall_max_max_{window}d"] = daily["weather_rainfall_max"].shift(1).rolling(window, min_periods=1).max()
        daily[f"weather_temp_avg_mean_{window}d"] = daily["weather_temp_avg"].shift(1).rolling(window, min_periods=1).mean()

    daily["weather_extreme_rain_flag"] = (daily["weather_rainfall_max"] >= 80).astype(int)
    daily["weather_heavy_rain_7d_flag"] = (daily["weather_rainfall_max_max_7d"] >= 80).astype(int)
    daily["weather_temp_range"] = daily["weather_temp_max"] - daily["weather_temp_min"]

    return daily.ffill().bfill()


def split_by_existing_dates(crop: str, merged: pd.DataFrame) -> None:
    train_dates = pd.read_csv(FORECAST_DIR / f"{crop}_daily_train.csv", usecols=["ds"], parse_dates=["ds"])
    test_dates = pd.read_csv(FORECAST_DIR / f"{crop}_daily_test.csv", usecols=["ds"], parse_dates=["ds"])
    train = merged[merged["ds"].isin(set(train_dates["ds"]))].copy()
    test = merged[merged["ds"].isin(set(test_dates["ds"]))].copy()
    merged.to_csv(OUT_DIR / f"{crop}_daily.csv", index=False, encoding="utf-8-sig")
    train.to_csv(OUT_DIR / f"{crop}_daily_train.csv", index=False, encoding="utf-8-sig")
    test.to_csv(OUT_DIR / f"{crop}_daily_test.csv", index=False, encoding="utf-8-sig")
    return len(train), len(test)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    weather = load_weather()
    summary = []

    for crop in CROPS:
        base = pd.read_csv(FORECAST_DIR / f"{crop}_daily.csv", parse_dates=["ds"])
        merged = base.merge(weather, on="ds", how="left").sort_values("ds")
        weather_cols = [c for c in weather.columns if c != "ds"]
        merged[weather_cols] = merged[weather_cols].ffill().bfill()
        train_n, test_n = split_by_existing_dates(crop, merged)
        summary.append((crop, len(merged), train_n, test_n))
        print(f"{crop}: rows={len(merged)}, train={train_n}, test={test_n}")

    lines = [
        "# Forecast data with weather",
        "",
        "Generated by `scripts/prepare_forecast_with_weather.py`.",
        "",
        "Weather source: `天氣資料.csv`.",
        "",
        "Weather is aggregated from county-level observations into daily national features.",
        "",
        "Added features include temperature, rainfall, humidity, lagged weather values, rolling rainfall, and extreme rain flags.",
        "",
        "| crop | rows | train | test |",
        "| --- | ---: | ---: | ---: |",
    ]
    for crop, rows, train_n, test_n in summary:
        lines.append(f"| {crop} | {rows} | {train_n} | {test_n} |")
    (OUT_DIR / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Done. Output: {OUT_DIR}")


if __name__ == "__main__":
    main()
